"""
Audits the analysis tables. 

This script establishes exactly what data are available for analysis. It:
- Checks the size and composition of the sample,
- Distinguishes missing review data from reviews with no annotations, 
- Summarises excluded assignments, and
- Determines how the models were distributed across packets

INPUTS

    outputs/document_analysis.csv
        One row per sample document, including document metadata, text
        lengths, review-data status and document-level annotation counts.

    outputs/annotation_analysis.csv
        One row per flattened category-field assignment, including the
        include_in_analysis decision.

OUTPUTS

    analysis_outputs/00_data_audit/DATA_AUDIT_README.md
        An explanation of the audit

    analysis_outputs/00_data_audit/tables/
        Four CSV outputs covering the headline audit, sample
        composition, document lengths and documents needing attention.

    analysis_outputs/00_data_audit/figures/en/
        Shareable PNG and SVG figures. English is generated by default; the
        shared language setting can later be expanded to include Spanish.
"""

import os
from pathlib import Path
import shutil

import matplotlib.pyplot as plt
import pandas as pd

from analysis_utils import (
    COLOURS,
    OUTPUT_LANGUAGES,
    add_chart_header,
    add_figure_note,
    apply_plot_style,
    check_required_files,
    coerce_boolean,
    create_output_folders,
    model_colour_map,
    save_figure,
    save_table,
)


# ---------------------------------------------------------------------------
# Set up the input and output paths
# ---------------------------------------------------------------------------

PROJECT_DIR = Path(
    os.environ.get("MODERNISATION_PROJECT_DIR", "/workspaces/modernisation")
)
INPUT_DIR = PROJECT_DIR / "outputs"
ANALYSIS_OUTPUT_DIR = PROJECT_DIR / "analysis_outputs"
SECTION_OUTPUT_DIR = ANALYSIS_OUTPUT_DIR / "00_data_audit"

DOCUMENT_ANALYSIS_PATH = INPUT_DIR / "document_analysis.csv"
ANNOTATION_ANALYSIS_PATH = INPUT_DIR / "annotation_analysis.csv"


# ---------------------------------------------------------------------------
# Define the wording used in each supported language
# ---------------------------------------------------------------------------

# Spanish wording can be added here before "es" is added to OUTPUT_LANGUAGES.
# Keeping the wording in the script makes every exported chart reproducible and
# avoids silently translating research terminology during execution.
CHART_TEXT = {
    "en": {
        "model_counts": {
            "title": "How is the document sample divided between the models?",
            "description": (
                "This check shows whether the two models are represented by "
                "similar numbers of documents in the analysis sample."
            ),
            "measure": "Number of sample documents assigned to each model.",
            "x_label": "Documents",
        },
        "review_status": {
            "title": "How much human-review data are available?",
            "description": (
                "This check separates completed reviews with annotations, "
                "completed reviews with no annotations, and unavailable "
                "annotation data."
            ),
            "measure": (
                "Documents with annotations recorded, no annotations "
                "recorded, or unavailable annotation data."
            ),
            "x_label": "Documents",
        },
        "packet_balance": {
            "title": "How are the models distributed across reviewer packets?",
            "description": (
                "This check identifies packets in which the allocation of the "
                "two models may be uneven."
            ),
            "measure": "Sample documents in each packet, split by model.",
            "x_label": "Reviewer packet",
            "y_label": "Documents",
        },
        "document_lengths": {
            "title": "Are document lengths comparable between the models?",
            "description": (
                "This check shows whether one model was evaluated on "
                "systematically longer modernised texts."
            ),
            "measure": "Distribution of modernised token counts by model.",
            "y_label": "Modernised tokens",
        },
    }
}


README_TEXT = """# 00 · Data audit

## What this section is trying to show

This section establishes exactly what data entered the analysis before any
claims are made about model performance. It checks the size and composition of
the document sample, the availability of the text and annotation files, the
distribution of documents between models and reviewer packets, and the effect
of annotation inclusion decisions.

The audit preserves the distinction between:

- a completed review in which the reviewer recorded no annotations; and
- a document for which the annotation JSON was unavailable.

The first is evidence of a reviewed document with zero recorded errors. The
second is missing review data and must not be counted as zero.

## Inputs

- `outputs/document_analysis.csv`: one row per sample document.
- `outputs/annotation_analysis.csv`: one row per category-field assignment.

## Tables produced by this script

The script creates four CSV files in
`analysis_outputs/00_data_audit/tables/`:

- `audit_summary.csv`: headline counts for the sample, available files and
  included or excluded annotation assignments.
- `sample_composition.csv`: document counts by model, archive, packet and
  reviewer, including the number with available annotation data.
- `document_length_summary_by_model.csv`: modernised token-count statistics by
  model.
- `documents_requiring_attention.csv`: documents with unavailable data or
  excluded annotation assignments.

## Figures produced by this script

- `documents_by_model`: sample size assigned to each model.
- `review_data_status`: completed and unavailable human-review data.
- `model_allocation_by_packet`: split of models across reviewer packets.
- `modernised_token_distribution_by_model`: document-length by model.

Each figure is saved as both PNG and SVG.

## Interpretation

Outputs are for quality-control and descriptive purposes. The substantive comparison begins in
`01_model_comparison`.
"""


# ---------------------------------------------------------------------------
# Check that Stage 8 has produced both analysis tables
# ---------------------------------------------------------------------------

check_required_files(
    [DOCUMENT_ANALYSIS_PATH, ANNOTATION_ANALYSIS_PATH],
    preceding_command="python scripts/construct_tables.py",
)


# ---------------------------------------------------------------------------
# Load and validate the analysis tables
# ---------------------------------------------------------------------------

documents_df = pd.read_csv(
    DOCUMENT_ANALYSIS_PATH,
    dtype={"filename_stem": "string"},
)

annotations_df = pd.read_csv(
    ANNOTATION_ANALYSIS_PATH,
    dtype={"filename_stem": "string"},
)

required_document_columns = {
    "filename_stem",
    "archive",
    "reviewer_packet",
    "reviewer_name",
    "model",
    "annotation_json_found",
    "modernised_text_available",
    "pre_modernisation_text_available",
    "review_data_status",
    "n_modernised_tokens",
    "n_included_assignments",
    "n_excluded_assignments",
}

required_annotation_columns = {
    "filename_stem",
    "annotation_id",
    "include_in_analysis",
}

missing_document_columns = required_document_columns - set(documents_df.columns)
missing_annotation_columns = required_annotation_columns - set(annotations_df.columns)

if missing_document_columns:
    raise ValueError(
        "document_analysis.csv is missing required columns: "
        f"{sorted(missing_document_columns)}."
    )

if missing_annotation_columns:
    raise ValueError(
        "annotation_analysis.csv is missing required columns: "
        f"{sorted(missing_annotation_columns)}."
    )

if documents_df["filename_stem"].duplicated().any():
    duplicates = documents_df.loc[
        documents_df["filename_stem"].duplicated(keep=False),
        "filename_stem",
    ]
    raise ValueError(
        "document_analysis.csv must contain one row per document. Duplicate "
        "filename_stem values were found:\n"
        f"{duplicates.to_string(index=False)}"
    )

for column in (
    "annotation_json_found",
    "modernised_text_available",
    "pre_modernisation_text_available",
):
    documents_df[column] = coerce_boolean(documents_df[column])

annotations_df["include_in_analysis"] = coerce_boolean(
    annotations_df["include_in_analysis"]
)

documents_df["reviewer_packet"] = pd.to_numeric(
    documents_df["reviewer_packet"], errors="raise"
).astype("Int64")


# ---------------------------------------------------------------------------
# Replace this section's previous outputs and create its explanatory README
# ---------------------------------------------------------------------------

# Remove only this script's own generated output directory before rebuilding
# it. This prevents tables or figures removed from the current design from
# lingering after a rerun and confusing readers.
if (
    SECTION_OUTPUT_DIR.name != "00_data_audit"
    or SECTION_OUTPUT_DIR.parent != ANALYSIS_OUTPUT_DIR
):
    raise RuntimeError(
        f"Unsafe to replace analysis output directory: {SECTION_OUTPUT_DIR}"
    )

if SECTION_OUTPUT_DIR.exists():
    shutil.rmtree(SECTION_OUTPUT_DIR)

tables_directory, figures_directory = create_output_folders(SECTION_OUTPUT_DIR)
SECTION_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
SECTION_README_PATH = (
    SECTION_OUTPUT_DIR / "DATA_AUDIT_README.md"
)

SECTION_README_PATH.write_text(
    README_TEXT,
    encoding="utf-8",
)


# ---------------------------------------------------------------------------
# Build and save the audit tables
# ---------------------------------------------------------------------------

review_available = documents_df["annotation_json_found"].fillna(False)
modernised_available = documents_df["modernised_text_available"].fillna(False)
pre_modernisation_available = documents_df[
    "pre_modernisation_text_available"
].fillna(False)

included_assignments = int(
    annotations_df["include_in_analysis"].fillna(False).sum()
)
excluded_assignments = int(
    (~annotations_df["include_in_analysis"].fillna(False)).sum()
)

audit_summary_df = pd.DataFrame(
    {
        "measure": [
            "sample_documents",
            "distinct_archives",
            "reviewer_packets",
            "reviewers",
            "models",
            "documents_with_annotation_data",
            "documents_without_annotation_data",
            "reviewed_documents_with_no_annotations",
            "modernised_texts_available",
            "pre_modernisation_texts_available",
            "recorded_assignment_rows",
            "included_assignment_rows",
            "excluded_assignment_rows",
        ],
        "value": [
            len(documents_df),
            documents_df["archive"].nunique(dropna=True),
            documents_df["reviewer_packet"].nunique(dropna=True),
            documents_df["reviewer_name"].nunique(dropna=True),
            documents_df["model"].nunique(dropna=True),
            int(review_available.sum()),
            int((~review_available).sum()),
            int(documents_df["review_data_status"].eq("reviewed_no_annotations").sum()),
            int(modernised_available.sum()),
            int(pre_modernisation_available.sum()),
            len(annotations_df),
            included_assignments,
            excluded_assignments,
        ],
    }
)
save_table(audit_summary_df, tables_directory / "audit_summary.csv")

# Combine the principal sample counts in one long-format table instead of
# producing separate model, archive, packet and reviewer CSV files. The
# grouping column makes each section easy to filter in a spreadsheet.
documents_by_model_df = (
    documents_df.assign(
        annotation_data_available=review_available,
        modernised_text_available=modernised_available,
    )
    .groupby("model", dropna=False, as_index=False)
    .agg(
        documents=("filename_stem", "size"),
        documents_with_annotation_data=("annotation_data_available", "sum"),
    )
    .rename(columns={"model": "group"})
)
documents_by_model_df.insert(0, "grouping", "model")

documents_by_archive_df = (
    documents_df.assign(annotation_data_available=review_available)
    .groupby("archive", dropna=False, as_index=False)
    .agg(
        documents=("filename_stem", "size"),
        documents_with_annotation_data=("annotation_data_available", "sum"),
    )
    .rename(columns={"archive": "group"})
    .sort_values(["documents", "group"], ascending=[False, True])
)
documents_by_archive_df.insert(0, "grouping", "archive")

documents_by_packet_df = (
    documents_df.groupby(
        ["reviewer_packet", "reviewer_name"],
        dropna=False,
        as_index=False,
    )
    .agg(
        documents=("filename_stem", "size"),
        documents_with_annotation_data=("annotation_json_found", "sum"),
    )
    .sort_values("reviewer_packet")
)
documents_by_packet_df["group"] = (
    "Packet "
    + documents_by_packet_df["reviewer_packet"].astype("string")
    + " · "
    + documents_by_packet_df["reviewer_name"].astype("string")
)
documents_by_packet_df.insert(0, "grouping", "packet_and_reviewer")
documents_by_packet_df = documents_by_packet_df[
    ["grouping", "group", "documents", "documents_with_annotation_data"]
]

sample_composition_df = pd.concat(
    [
        documents_by_model_df,
        documents_by_archive_df,
        documents_by_packet_df,
    ],
    ignore_index=True,
)

save_table(
    sample_composition_df,
    tables_directory / "sample_composition.csv",
)

# This summary is needed to draw the packet-allocation figure. It is not saved
# as another CSV because the underlying packet totals are already represented
# in sample_composition.csv.
model_by_packet_df = (
    documents_df.groupby(
        ["reviewer_packet", "reviewer_name", "model"],
        dropna=False,
        as_index=False,
    )
    .agg(documents=("filename_stem", "size"))
    .sort_values(["reviewer_packet", "model"])
)

length_summary_df = (
    documents_df.groupby("model", dropna=False)["n_modernised_tokens"]
    .agg(
        documents_with_token_count="count",
        minimum="min",
        first_quartile=lambda values: values.quantile(0.25),
        median="median",
        mean="mean",
        third_quartile=lambda values: values.quantile(0.75),
        maximum="max",
    )
    .reset_index()
)
save_table(
    length_summary_df,
    tables_directory / "document_length_summary_by_model.csv",
)

documents_requiring_attention_df = documents_df.loc[
    (~review_available)
    | (~modernised_available)
    | (~pre_modernisation_available)
    | documents_df["n_excluded_assignments"].fillna(0).gt(0),
    [
        "filename_stem",
        "archive",
        "reviewer_packet",
        "reviewer_name",
        "model",
        "review_data_status",
        "annotation_json_found",
        "modernised_text_available",
        "pre_modernisation_text_available",
        "n_excluded_assignments",
    ],
].copy()

save_table(
    documents_requiring_attention_df,
    tables_directory / "documents_requiring_attention.csv",
)


# ---------------------------------------------------------------------------
# Apply the shared chart style and generate the audit figures
# ---------------------------------------------------------------------------

apply_plot_style()
model_colours = model_colour_map(documents_df["model"])

for language in OUTPUT_LANGUAGES:
    if language not in CHART_TEXT:
        raise ValueError(
            f"No audit chart wording has been supplied for language: {language}."
        )

    language_directory = figures_directory / language
    text = CHART_TEXT[language]

    # Figure 1: document sample by model.
    model_counts = (
        documents_df["model"].value_counts(dropna=False).sort_index()
    )
    model_labels = [str(label) for label in model_counts.index]
    colours = [model_colours.get(label, COLOURS["gold"]) for label in model_labels]

    fig, ax = plt.subplots(figsize=(10, 6.8))
    fig.subplots_adjust(top=0.72, bottom=0.16, left=0.30, right=0.92)
    bars = ax.barh(model_labels, model_counts.values, color=colours, height=0.58)
    ax.set_xlabel(text["model_counts"]["x_label"])
    ax.grid(axis="x")
    ax.set_axisbelow(True)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.tick_params(axis="y", length=0)
    ax.bar_label(bars, padding=5, fontsize=10, fontweight="bold")
    ax.set_xlim(0, max(model_counts.max() * 1.14, 1))
    add_chart_header(fig, **{key: text["model_counts"][key] for key in ("title", "description", "measure")})
    add_figure_note(fig, "This figure describes allocation only; it does not compare model performance.")
    save_figure(fig, language_directory, "documents_by_model")

    # Figure 2: review-data status.
    preferred_status_order = [
        "reviewed_with_annotations",
        "reviewed_no_annotations",
        "annotation_data_unavailable",
    ]
    status_labels = {
        "reviewed_with_annotations": "Reviewed · annotations recorded",
        "reviewed_no_annotations": "Reviewed · no annotations recorded",
        "annotation_data_unavailable": "Annotation data unavailable",
    }
    status_counts = (
        documents_df["review_data_status"]
        .value_counts()
        .reindex(preferred_status_order, fill_value=0)
    )
    status_colours = [
        COLOURS["gold"],
        COLOURS["gold_light"],
        COLOURS["missing"],
    ]

    fig, ax = plt.subplots(figsize=(10, 6.8))
    fig.subplots_adjust(top=0.72, bottom=0.16, left=0.34, right=0.92)
    bars = ax.barh(
        [status_labels[status] for status in preferred_status_order][::-1],
        status_counts.values[::-1],
        color=status_colours[::-1],
        height=0.58,
    )
    ax.set_xlabel(text["review_status"]["x_label"])
    ax.grid(axis="x")
    ax.set_axisbelow(True)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.tick_params(axis="y", length=0)
    ax.bar_label(bars, padding=5, fontsize=10, fontweight="bold")
    ax.set_xlim(0, max(status_counts.max() * 1.14, 1))
    add_chart_header(fig, **{key: text["review_status"][key] for key in ("title", "description", "measure")})
    add_figure_note(
        fig,
        "Unavailable annotation data are missing review results and are not treated as zero-error documents.",
    )
    save_figure(fig, language_directory, "review_data_status")

    # Figure 3: model allocation within each reviewer packet.
    packet_pivot = (
        model_by_packet_df.pivot(
            index="reviewer_packet",
            columns="model",
            values="documents",
        )
        .fillna(0)
        .sort_index()
    )

    fig, ax = plt.subplots(figsize=(11, 7.2))
    fig.subplots_adjust(top=0.72, bottom=0.20, left=0.10, right=0.92)
    bottom = pd.Series(0, index=packet_pivot.index, dtype=float)
    for model in packet_pivot.columns:
        values = packet_pivot[model].astype(float)
        ax.bar(
            packet_pivot.index.astype(str),
            values,
            bottom=bottom,
            label=str(model),
            color=model_colours.get(str(model), COLOURS["gold"]),
            width=0.67,
        )
        bottom = bottom + values

    ax.set_xlabel(text["packet_balance"]["x_label"])
    ax.set_ylabel(text["packet_balance"]["y_label"])
    ax.grid(axis="y")
    ax.set_axisbelow(True)
    ax.spines[["top", "right"]].set_visible(False)
    ax.legend(
        frameon=False,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.055),
        bbox_transform=fig.transFigure,
        ncol=2,
    )
    add_chart_header(fig, **{key: text["packet_balance"][key] for key in ("title", "description", "measure")})
    add_figure_note(fig, "Each packet was assigned to one reviewer; this figure checks model allocation, not reviewer performance.")
    save_figure(fig, language_directory, "model_allocation_by_packet")

    # Figure 4: modernised token-count distribution by model.
    models = [str(model) for model in documents_df["model"].dropna().unique()]
    models = sorted(models)
    token_groups = [
        documents_df.loc[
            documents_df["model"].astype(str).eq(model),
            "n_modernised_tokens",
        ].dropna()
        for model in models
    ]

    fig, ax = plt.subplots(figsize=(10, 7.2))
    fig.subplots_adjust(top=0.72, bottom=0.22, left=0.14, right=0.92)
    boxplot = ax.boxplot(
        token_groups,
        tick_labels=models,
        patch_artist=True,
        widths=0.55,
        medianprops={"color": COLOURS["text"], "linewidth": 1.8},
        whiskerprops={"color": COLOURS["muted_text"]},
        capprops={"color": COLOURS["muted_text"]},
        flierprops={
            "marker": "o",
            "markerfacecolor": COLOURS["panel"],
            "markeredgecolor": COLOURS["muted_text"],
            "markersize": 4,
        },
    )
    for patch, model in zip(boxplot["boxes"], models):
        patch.set_facecolor(model_colours.get(model, COLOURS["gold"]))
        patch.set_edgecolor("none")
        patch.set_alpha(0.92)

    ax.set_ylabel(text["document_lengths"]["y_label"])
    ax.grid(axis="y")
    ax.set_axisbelow(True)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(axis="x", labelrotation=12)
    add_chart_header(fig, **{key: text["document_lengths"][key] for key in ("title", "description", "measure")})
    add_figure_note(fig, "Token counts use the reproducible Unicode word rule defined in 07_build_document_features.py.")
    save_figure(
        fig,
        language_directory,
        "modernised_token_distribution_by_model",
    )


# ---------------------------------------------------------------------------
# Brief report on completion
# ---------------------------------------------------------------------------

print(f"\nSample documents audited: {len(documents_df)}")
print(f"Documents with annotation data: {int(review_available.sum())}")
print(f"Documents without annotation data: {int((~review_available).sum())}")
print(f"Included assignment rows: {included_assignments}")
print(f"Excluded assignment rows: {excluded_assignments}")
print(f"\nTables saved to: {tables_directory}")
print(f"Figures saved to: {figures_directory}")
print(f"README saved to: {SECTION_README_PATH}")
